version: '3'

services: 
  anon-chat:
    container_name: anon-chat
    build: .
    environment: 
      - TZ=Asia/Bangkok
    working_dir: /app
    command: ["sh", "/app/anon-chat"]
    ports: 
      - "3001:3001"
    depends_on:
      - "postgres"
    links: 
      - "postgres"

  postgres:
    container_name: postgres
    image: postgres:11.2-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=anonchat
      - TZ=Asia/Bangkok
    ports:
      - "5434:5432"      